import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionProvider from "./components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <SessionProvider>
          <div className="flex flex-col min-h-screen">
            <nav className="container mx-auto sticky top-0 right-0 left-0 z-50 bg-black">
              <Navbar></Navbar>
            </nav>
            <div className="container mx-auto px-2 flex-1">{children}</div>
            <footer>
              <Footer></Footer>
            </footer>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
